name: Bump version number
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  bumpversion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Bump version number
        run: |
          new_version=$(nix develop .#ci --command bash -c "version:bump nix/packages/hledger-merge/default.nix")
          # git push if we have a diff
          if [[ -n $(git diff) ]]; then
            git add nix/packages/hledger-merge/default.nix
            git config --global user.email "<github-actions[bot]@users.noreply.github.com>"
            git config --global user.name "github-actions[bot]"
            git commit -m "chore: bump version to $new_version [skip ci][no bump]"
            git tag -a "v$new_version" -m "v$new_version"
            git push origin main --tags
          fi
